// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  noticeId: __t.u64().primaryKey().name("notice_id"),
  roomId: __t.string().name("room_id"),
  noticeType: __t.string().name("notice_type"),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
