// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  summaryKey: __t.string().primaryKey().name("summary_key"),
  roomId: __t.string().name("room_id"),
  playerUsernameKey: __t.string().name("player_username_key"),
  playerUsername: __t.string().name("player_username"),
  opponentUsernameKey: __t.string().name("opponent_username_key"),
  opponentUsername: __t.string().name("opponent_username"),
  opponentEloBefore: __t.u64().name("opponent_elo_before"),
  opponentLeague: __t.string().name("opponent_league"),
  winner: __t.string(),
  pointsScored: __t.u64().name("points_scored"),
  deltaRating: __t.i64().name("delta_rating"),
  playerEloBefore: __t.u64().name("player_elo_before"),
  playerEloAfter: __t.u64().name("player_elo_after"),
  playerLeagueAfter: __t.string().name("player_league_after"),
  createdAt: __t.timestamp().name("created_at"),
});
