// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  selectionKey: __t.string().primaryKey().name("selection_key"),
  roomId: __t.string().name("room_id"),
  playerIdentity: __t.identity().name("player_identity"),
  powerupId: __t.string().name("powerup_id"),
  lockedAt: __t.timestamp().name("locked_at"),
});
