// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  selectionKey: __t.string().primaryKey().name("selection_key"),
  roomId: __t.string().name("room_id"),
  playerIdentity: __t.identity().name("player_identity"),
  powerupId: __t.option(__t.string()).name("powerup_id"),
  isReady: __t.bool().name("is_ready"),
  hasLockedPower: __t.bool().name("has_locked_power"),
  activeDebuffs: __t.array(__t.string()).name("active_debuffs"),
  hasSubmitted: __t.bool().name("has_submitted"),
  isTyping: __t.bool().name("is_typing"),
  lockedAt: __t.option(__t.timestamp()).name("locked_at"),
  appliedAtRoundStartAt: __t.option(__t.timestamp()).name("applied_at_round_start_at"),
  playerRoundStartTime: __t.option(__t.timestamp()).name("player_round_start_time"),
  playerRoundEndTime: __t.option(__t.timestamp()).name("player_round_end_time"),
});
