// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roundProblemKey: __t.string().primaryKey().name("round_problem_key"),
  roomId: __t.string().name("room_id"),
  roundNumber: __t.u64().name("round_number"),
  problemApiUrl: __t.string().name("problem_api_url"),
  problemJson: __t.string().name("problem_json"),
  fetchedAt: __t.timestamp().name("fetched_at"),
});
