// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  roomId: __t.string().name("room_id"),
  roundNumber: __t.u64().name("round_number"),
  sourcePlayerIdentity: __t.identity().name("source_player_identity"),
  targetPlayerIdentity: __t.identity().name("target_player_identity"),
  powerupId: __t.string().name("powerup_id"),
  createdAt: __t.timestamp().name("created_at"),
});
