// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memberId: __t.u64().primaryKey().name("member_id"),
  roomId: __t.string().name("room_id"),
  memberIdentity: __t.identity().name("member_identity"),
  memberName: __t.string().name("member_name"),
  membershipKey: __t.string().name("membership_key"),
  joinedAt: __t.timestamp().name("joined_at"),
});
