// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  creatorIdentity: __t.identity().name("creator_identity"),
  creatorName: __t.string().name("creator_name"),
  matchState: __t.string().name("match_state"),
  draftPlayerOneIdentity: __t.option(__t.identity()).name("draft_player_one_identity"),
  draftPlayerTwoIdentity: __t.option(__t.identity()).name("draft_player_two_identity"),
  rolledPowers: __t.array(__t.string()).name("rolled_powers"),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
});
