// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionIdentity: __t.identity().primaryKey().name("session_identity"),
  userSlug: __t.string().name("user_slug"),
  username: __t.string(),
  connected: __t.bool(),
  authenticatedAt: __t.timestamp().name("authenticated_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
