// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import AcceptGameInviteReducer from "./accept_game_invite_reducer";
import BeginPlayingRoundReducer from "./begin_playing_round_reducer";
import CacheRoundProblemReducer from "./cache_round_problem_reducer";
import CancelFriendRequestReducer from "./cancel_friend_request_reducer";
import CancelGameInviteReducer from "./cancel_game_invite_reducer";
import CreateArenaRoomReducer from "./create_arena_room_reducer";
import DeclineFriendRequestReducer from "./decline_friend_request_reducer";
import DeclineGameInviteReducer from "./decline_game_invite_reducer";
import DeleteArenaRoomReducer from "./delete_arena_room_reducer";
import JoinArenaRoomReducer from "./join_arena_room_reducer";
import KickArenaMemberReducer from "./kick_arena_member_reducer";
import LeaveArenaRoomReducer from "./leave_arena_room_reducer";
import LockArenaPowerupReducer from "./lock_arena_powerup_reducer";
import LogInReducer from "./log_in_reducer";
import LogOutReducer from "./log_out_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendGameInviteReducer from "./send_game_invite_reducer";
import SetPlayerActivityReducer from "./set_player_activity_reducer";
import SignUpReducer from "./sign_up_reducer";
import StartArenaMatchReducer from "./start_arena_match_reducer";
import SubmitRoundResultReducer from "./submit_round_result_reducer";
import TriggerArenaSabotageReducer from "./trigger_arena_sabotage_reducer";
import UnlockArenaPowerupReducer from "./unlock_arena_powerup_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ArenaMatchContinueRow from "./arena_match_continue_table";
import ArenaMatchSummaryRow from "./arena_match_summary_table";
import ArenaPowerupLockRow from "./arena_powerup_lock_table";
import ArenaRoomRow from "./arena_room_table";
import ArenaRoomMemberRow from "./arena_room_member_table";
import ArenaRoomNoticeRow from "./arena_room_notice_table";
import ArenaRoundProblemRow from "./arena_round_problem_table";
import ArenaRoundResultRow from "./arena_round_result_table";
import ArenaSabotageEventRow from "./arena_sabotage_event_table";
import AuthSessionRow from "./auth_session_table";
import FriendRequestRow from "./friend_request_table";
import FriendshipRow from "./friendship_table";
import GameInviteRow from "./game_invite_table";
import PlayerPresenceRow from "./player_presence_table";
import PlayerProfileRow from "./player_profile_table";
import RivalEntryRow from "./rival_entry_table";
import UserNotificationRow from "./user_notification_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  arenaMatchContinue: __table({
    name: 'arena_match_continue',
    indexes: [
      { accessor: 'continueKey', name: 'arena_match_continue_continue_key_idx_btree', algorithm: 'btree', columns: [
        'continueKey',
      ] },
      { accessor: 'arena_match_continue_room_id', name: 'arena_match_continue_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'arena_match_continue_continue_key_key', constraint: 'unique', columns: ['continueKey'] },
    ],
  }, ArenaMatchContinueRow),
  arenaMatchSummary: __table({
    name: 'arena_match_summary',
    indexes: [
      { accessor: 'arena_match_summary_player_username_key', name: 'arena_match_summary_player_username_key_idx_btree', algorithm: 'btree', columns: [
        'playerUsernameKey',
      ] },
      { accessor: 'summaryKey', name: 'arena_match_summary_summary_key_idx_btree', algorithm: 'btree', columns: [
        'summaryKey',
      ] },
    ],
    constraints: [
      { name: 'arena_match_summary_summary_key_key', constraint: 'unique', columns: ['summaryKey'] },
    ],
  }, ArenaMatchSummaryRow),
  arenaPowerupLock: __table({
    name: 'arena_powerup_lock',
    indexes: [
      { accessor: 'arena_powerup_lock_room_id', name: 'arena_powerup_lock_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'selectionKey', name: 'arena_powerup_lock_selection_key_idx_btree', algorithm: 'btree', columns: [
        'selectionKey',
      ] },
    ],
    constraints: [
      { name: 'arena_powerup_lock_selection_key_key', constraint: 'unique', columns: ['selectionKey'] },
    ],
  }, ArenaPowerupLockRow),
  arenaRoom: __table({
    name: 'arena_room',
    indexes: [
      { accessor: 'roomId', name: 'arena_room_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'arena_room_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, ArenaRoomRow),
  arenaRoomMember: __table({
    name: 'arena_room_member',
    indexes: [
      { accessor: 'memberId', name: 'arena_room_member_member_id_idx_btree', algorithm: 'btree', columns: [
        'memberId',
      ] },
      { accessor: 'membershipKey', name: 'arena_room_member_membership_key_idx_btree', algorithm: 'btree', columns: [
        'membershipKey',
      ] },
    ],
    constraints: [
      { name: 'arena_room_member_member_id_key', constraint: 'unique', columns: ['memberId'] },
      { name: 'arena_room_member_membership_key_key', constraint: 'unique', columns: ['membershipKey'] },
    ],
  }, ArenaRoomMemberRow),
  arenaRoomNotice: __table({
    name: 'arena_room_notice',
    indexes: [
      { accessor: 'noticeId', name: 'arena_room_notice_notice_id_idx_btree', algorithm: 'btree', columns: [
        'noticeId',
      ] },
    ],
    constraints: [
      { name: 'arena_room_notice_notice_id_key', constraint: 'unique', columns: ['noticeId'] },
    ],
  }, ArenaRoomNoticeRow),
  arenaRoundProblem: __table({
    name: 'arena_round_problem',
    indexes: [
      { accessor: 'arena_round_problem_room_id', name: 'arena_round_problem_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'roundProblemKey', name: 'arena_round_problem_round_problem_key_idx_btree', algorithm: 'btree', columns: [
        'roundProblemKey',
      ] },
    ],
    constraints: [
      { name: 'arena_round_problem_round_problem_key_key', constraint: 'unique', columns: ['roundProblemKey'] },
    ],
  }, ArenaRoundProblemRow),
  arenaRoundResult: __table({
    name: 'arena_round_result',
    indexes: [
      { accessor: 'resultKey', name: 'arena_round_result_result_key_idx_btree', algorithm: 'btree', columns: [
        'resultKey',
      ] },
      { accessor: 'arena_round_result_room_id', name: 'arena_round_result_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'arena_round_result_result_key_key', constraint: 'unique', columns: ['resultKey'] },
    ],
  }, ArenaRoundResultRow),
  arenaSabotageEvent: __table({
    name: 'arena_sabotage_event',
    indexes: [
      { accessor: 'eventId', name: 'arena_sabotage_event_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { accessor: 'arena_sabotage_event_room_id', name: 'arena_sabotage_event_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'arena_sabotage_event_target_player_identity', name: 'arena_sabotage_event_target_player_identity_idx_btree', algorithm: 'btree', columns: [
        'targetPlayerIdentity',
      ] },
    ],
    constraints: [
      { name: 'arena_sabotage_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
    event: true,
  }, ArenaSabotageEventRow),
  authSession: __table({
    name: 'auth_session',
    indexes: [
      { accessor: 'sessionIdentity', name: 'auth_session_session_identity_idx_btree', algorithm: 'btree', columns: [
        'sessionIdentity',
      ] },
    ],
    constraints: [
      { name: 'auth_session_session_identity_key', constraint: 'unique', columns: ['sessionIdentity'] },
    ],
  }, AuthSessionRow),
  friendRequest: __table({
    name: 'friend_request',
    indexes: [
      { accessor: 'friend_request_from_identity', name: 'friend_request_from_identity_idx_btree', algorithm: 'btree', columns: [
        'fromIdentity',
      ] },
      { accessor: 'requestId', name: 'friend_request_request_id_idx_btree', algorithm: 'btree', columns: [
        'requestId',
      ] },
      { accessor: 'friend_request_status', name: 'friend_request_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'friend_request_to_identity', name: 'friend_request_to_identity_idx_btree', algorithm: 'btree', columns: [
        'toIdentity',
      ] },
    ],
    constraints: [
      { name: 'friend_request_request_id_key', constraint: 'unique', columns: ['requestId'] },
    ],
  }, FriendRequestRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { accessor: 'friendshipKey', name: 'friendship_friendship_key_idx_btree', algorithm: 'btree', columns: [
        'friendshipKey',
      ] },
      { accessor: 'friendship_user_a', name: 'friendship_user_a_idx_btree', algorithm: 'btree', columns: [
        'userA',
      ] },
      { accessor: 'friendship_user_b', name: 'friendship_user_b_idx_btree', algorithm: 'btree', columns: [
        'userB',
      ] },
    ],
    constraints: [
      { name: 'friendship_friendship_key_key', constraint: 'unique', columns: ['friendshipKey'] },
    ],
  }, FriendshipRow),
  gameInvite: __table({
    name: 'game_invite',
    indexes: [
      { accessor: 'game_invite_from_identity', name: 'game_invite_from_identity_idx_btree', algorithm: 'btree', columns: [
        'fromIdentity',
      ] },
      { accessor: 'inviteId', name: 'game_invite_invite_id_idx_btree', algorithm: 'btree', columns: [
        'inviteId',
      ] },
      { accessor: 'game_invite_room_id', name: 'game_invite_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'game_invite_status', name: 'game_invite_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'game_invite_to_identity', name: 'game_invite_to_identity_idx_btree', algorithm: 'btree', columns: [
        'toIdentity',
      ] },
    ],
    constraints: [
      { name: 'game_invite_invite_id_key', constraint: 'unique', columns: ['inviteId'] },
    ],
  }, GameInviteRow),
  playerPresence: __table({
    name: 'player_presence',
    indexes: [
      { accessor: 'player_presence_activity', name: 'player_presence_activity_idx_btree', algorithm: 'btree', columns: [
        'activity',
      ] },
      { accessor: 'playerIdentity', name: 'player_presence_player_identity_idx_btree', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'player_presence_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, PlayerPresenceRow),
  playerProfile: __table({
    name: 'player_profile',
    indexes: [
      { accessor: 'usernameKey', name: 'player_profile_username_key_idx_btree', algorithm: 'btree', columns: [
        'usernameKey',
      ] },
    ],
    constraints: [
      { name: 'player_profile_username_key_key', constraint: 'unique', columns: ['usernameKey'] },
    ],
  }, PlayerProfileRow),
  rivalEntry: __table({
    name: 'rival_entry',
    indexes: [
      { accessor: 'rival_entry_owner_identity', name: 'rival_entry_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
      { accessor: 'rival_entry_rival_identity', name: 'rival_entry_rival_identity_idx_btree', algorithm: 'btree', columns: [
        'rivalIdentity',
      ] },
      { accessor: 'rivalKey', name: 'rival_entry_rival_key_idx_btree', algorithm: 'btree', columns: [
        'rivalKey',
      ] },
    ],
    constraints: [
      { name: 'rival_entry_rival_key_key', constraint: 'unique', columns: ['rivalKey'] },
    ],
  }, RivalEntryRow),
  userNotification: __table({
    name: 'user_notification',
    indexes: [
      { accessor: 'user_notification_friend_request_id', name: 'user_notification_friend_request_id_idx_btree', algorithm: 'btree', columns: [
        'friendRequestId',
      ] },
      { accessor: 'user_notification_invite_id', name: 'user_notification_invite_id_idx_btree', algorithm: 'btree', columns: [
        'inviteId',
      ] },
      { accessor: 'notificationId', name: 'user_notification_notification_id_idx_btree', algorithm: 'btree', columns: [
        'notificationId',
      ] },
      { accessor: 'user_notification_recipient_identity', name: 'user_notification_recipient_identity_idx_btree', algorithm: 'btree', columns: [
        'recipientIdentity',
      ] },
    ],
    constraints: [
      { name: 'user_notification_notification_id_key', constraint: 'unique', columns: ['notificationId'] },
    ],
  }, UserNotificationRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("accept_game_invite", AcceptGameInviteReducer),
  __reducerSchema("begin_playing_round", BeginPlayingRoundReducer),
  __reducerSchema("cache_round_problem", CacheRoundProblemReducer),
  __reducerSchema("cancel_friend_request", CancelFriendRequestReducer),
  __reducerSchema("cancel_game_invite", CancelGameInviteReducer),
  __reducerSchema("create_arena_room", CreateArenaRoomReducer),
  __reducerSchema("decline_friend_request", DeclineFriendRequestReducer),
  __reducerSchema("decline_game_invite", DeclineGameInviteReducer),
  __reducerSchema("delete_arena_room", DeleteArenaRoomReducer),
  __reducerSchema("join_arena_room", JoinArenaRoomReducer),
  __reducerSchema("kick_arena_member", KickArenaMemberReducer),
  __reducerSchema("leave_arena_room", LeaveArenaRoomReducer),
  __reducerSchema("lock_arena_powerup", LockArenaPowerupReducer),
  __reducerSchema("log_in", LogInReducer),
  __reducerSchema("log_out", LogOutReducer),
  __reducerSchema("mark_notification_read", MarkNotificationReadReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_game_invite", SendGameInviteReducer),
  __reducerSchema("set_player_activity", SetPlayerActivityReducer),
  __reducerSchema("sign_up", SignUpReducer),
  __reducerSchema("start_arena_match", StartArenaMatchReducer),
  __reducerSchema("submit_round_result", SubmitRoundResultReducer),
  __reducerSchema("trigger_arena_sabotage", TriggerArenaSabotageReducer),
  __reducerSchema("unlock_arena_powerup", UnlockArenaPowerupReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

