// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  usernameKey: __t.string().primaryKey().name("username_key"),
  username: __t.string(),
  eloRating: __t.u64().name("elo_rating"),
  matchesPlayed: __t.u64().name("matches_played"),
  wins: __t.u64(),
  losses: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
