// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rivalKey: __t.string().primaryKey().name("rival_key"),
  ownerIdentity: __t.identity().name("owner_identity"),
  rivalIdentity: __t.identity().name("rival_identity"),
  rivalUsername: __t.string().name("rival_username"),
  createdAt: __t.timestamp().name("created_at"),
  lastMatchedAt: __t.timestamp().name("last_matched_at"),
});
