// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AuthAccount = __t.object("AuthAccount", {
  id: __t.u64(),
  userSlug: __t.string(),
  username: __t.string(),
  usernameKey: __t.string(),
  email: __t.string(),
  passwordDigest: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AuthAccount = __Infer<typeof AuthAccount>;

export const AuthSession = __t.object("AuthSession", {
  sessionIdentity: __t.identity(),
  userSlug: __t.string(),
  username: __t.string(),
  connected: __t.bool(),
  authenticatedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type AuthSession = __Infer<typeof AuthSession>;

