// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArenaRoom = __t.object("ArenaRoom", {
  roomId: __t.string(),
  creatorIdentity: __t.identity(),
  creatorName: __t.string(),
  matchState: __t.string(),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
});
export type ArenaRoom = __Infer<typeof ArenaRoom>;

export const ArenaRoomMember = __t.object("ArenaRoomMember", {
  memberId: __t.u64(),
  roomId: __t.string(),
  memberIdentity: __t.identity(),
  memberName: __t.string(),
  membershipKey: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ArenaRoomMember = __Infer<typeof ArenaRoomMember>;

export const ArenaRoomNotice = __t.object("ArenaRoomNotice", {
  noticeId: __t.u64(),
  roomId: __t.string(),
  noticeType: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type ArenaRoomNotice = __Infer<typeof ArenaRoomNotice>;

export const ArenaRoomTimeoutJob = __t.object("ArenaRoomTimeoutJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.string(),
});
export type ArenaRoomTimeoutJob = __Infer<typeof ArenaRoomTimeoutJob>;

export const AuthAccount = __t.object("AuthAccount", {
  id: __t.u64(),
  userSlug: __t.string(),
  username: __t.string(),
  usernameKey: __t.string(),
  email: __t.string(),
  passwordDigest: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AuthAccount = __Infer<typeof AuthAccount>;

export const AuthSession = __t.object("AuthSession", {
  sessionIdentity: __t.identity(),
  userSlug: __t.string(),
  username: __t.string(),
  connected: __t.bool(),
  authenticatedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type AuthSession = __Infer<typeof AuthSession>;

