// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArenaPowerupLock = __t.object("ArenaPowerupLock", {
  selectionKey: __t.string(),
  roomId: __t.string(),
  playerIdentity: __t.identity(),
  powerupId: __t.option(__t.string()),
  isReady: __t.bool(),
  hasLockedPower: __t.bool(),
  activeDebuffs: __t.array(__t.string()),
  hasSubmitted: __t.bool(),
  isTyping: __t.bool(),
  lockedAt: __t.option(__t.timestamp()),
});
export type ArenaPowerupLock = __Infer<typeof ArenaPowerupLock>;

export const ArenaRoom = __t.object("ArenaRoom", {
  roomId: __t.string(),
  creatorIdentity: __t.identity(),
  creatorName: __t.string(),
  matchState: __t.string(),
  currentRound: __t.u64(),
  currentQuestionId: __t.option(__t.string()),
  draftPlayerOneIdentity: __t.option(__t.identity()),
  draftPlayerTwoIdentity: __t.option(__t.identity()),
  rolledPowers: __t.array(__t.string()),
  roundStartTime: __t.option(__t.timestamp()),
  roundEndTime: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
});
export type ArenaRoom = __Infer<typeof ArenaRoom>;

export const ArenaRoomMember = __t.object("ArenaRoomMember", {
  memberId: __t.u64(),
  roomId: __t.string(),
  memberIdentity: __t.identity(),
  memberName: __t.string(),
  membershipKey: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ArenaRoomMember = __Infer<typeof ArenaRoomMember>;

export const ArenaRoomNotice = __t.object("ArenaRoomNotice", {
  noticeId: __t.u64(),
  roomId: __t.string(),
  noticeType: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type ArenaRoomNotice = __Infer<typeof ArenaRoomNotice>;

export const ArenaRoomTimeoutJob = __t.object("ArenaRoomTimeoutJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.string(),
});
export type ArenaRoomTimeoutJob = __Infer<typeof ArenaRoomTimeoutJob>;

export const ArenaRoundResult = __t.object("ArenaRoundResult", {
  resultKey: __t.string(),
  roomId: __t.string(),
  playerIdentity: __t.identity(),
  roundNumber: __t.u64(),
  powerUsed: __t.string(),
  timeTakenSeconds: __t.u64(),
  testcasesPassed: __t.u64(),
  totalTestcases: __t.u64(),
  pointsEarned: __t.u64(),
  createdAt: __t.timestamp(),
});
export type ArenaRoundResult = __Infer<typeof ArenaRoundResult>;

export const AuthAccount = __t.object("AuthAccount", {
  id: __t.u64(),
  username: __t.string(),
  usernameKey: __t.string(),
  email: __t.string(),
  passwordDigest: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AuthAccount = __Infer<typeof AuthAccount>;

export const AuthSession = __t.object("AuthSession", {
  sessionIdentity: __t.identity(),
  username: __t.string(),
  connected: __t.bool(),
  authenticatedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type AuthSession = __Infer<typeof AuthSession>;

