// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  notificationId: __t.string().primaryKey().name("notification_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  notificationType: __t.string().name("notification_type"),
  actorIdentity: __t.option(__t.identity()).name("actor_identity"),
  roomId: __t.option(__t.string()).name("room_id"),
  inviteId: __t.option(__t.string()).name("invite_id"),
  friendRequestId: __t.option(__t.string()).name("friend_request_id"),
  message: __t.string(),
  isRead: __t.bool().name("is_read"),
  createdAt: __t.timestamp().name("created_at"),
  readAt: __t.option(__t.timestamp()).name("read_at"),
});
