// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LogInReducer from "../log_in_reducer";
import LogOutReducer from "../log_out_reducer";
import SignUpReducer from "../sign_up_reducer";

export type LogInParams = __Infer<typeof LogInReducer>;
export type LogOutParams = __Infer<typeof LogOutReducer>;
export type SignUpParams = __Infer<typeof SignUpReducer>;

