// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "../accept_friend_request_reducer";
import AcceptGameInviteReducer from "../accept_game_invite_reducer";
import BeginPlayingRoundReducer from "../begin_playing_round_reducer";
import CacheRoundProblemReducer from "../cache_round_problem_reducer";
import CancelFriendRequestReducer from "../cancel_friend_request_reducer";
import CancelGameInviteReducer from "../cancel_game_invite_reducer";
import CreateArenaRoomReducer from "../create_arena_room_reducer";
import DeclineFriendRequestReducer from "../decline_friend_request_reducer";
import DeclineGameInviteReducer from "../decline_game_invite_reducer";
import DeleteArenaRoomReducer from "../delete_arena_room_reducer";
import JoinArenaRoomReducer from "../join_arena_room_reducer";
import KickArenaMemberReducer from "../kick_arena_member_reducer";
import LeaveArenaRoomReducer from "../leave_arena_room_reducer";
import LockArenaPowerupReducer from "../lock_arena_powerup_reducer";
import LogInReducer from "../log_in_reducer";
import LogOutReducer from "../log_out_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import RemoveFriendReducer from "../remove_friend_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SendGameInviteReducer from "../send_game_invite_reducer";
import SetPlayerActivityReducer from "../set_player_activity_reducer";
import SignUpReducer from "../sign_up_reducer";
import StartArenaMatchReducer from "../start_arena_match_reducer";
import SubmitRoundResultReducer from "../submit_round_result_reducer";
import TriggerArenaSabotageReducer from "../trigger_arena_sabotage_reducer";
import UnlockArenaPowerupReducer from "../unlock_arena_powerup_reducer";

export type AcceptFriendRequestParams = __Infer<typeof AcceptFriendRequestReducer>;
export type AcceptGameInviteParams = __Infer<typeof AcceptGameInviteReducer>;
export type BeginPlayingRoundParams = __Infer<typeof BeginPlayingRoundReducer>;
export type CacheRoundProblemParams = __Infer<typeof CacheRoundProblemReducer>;
export type CancelFriendRequestParams = __Infer<typeof CancelFriendRequestReducer>;
export type CancelGameInviteParams = __Infer<typeof CancelGameInviteReducer>;
export type CreateArenaRoomParams = __Infer<typeof CreateArenaRoomReducer>;
export type DeclineFriendRequestParams = __Infer<typeof DeclineFriendRequestReducer>;
export type DeclineGameInviteParams = __Infer<typeof DeclineGameInviteReducer>;
export type DeleteArenaRoomParams = __Infer<typeof DeleteArenaRoomReducer>;
export type JoinArenaRoomParams = __Infer<typeof JoinArenaRoomReducer>;
export type KickArenaMemberParams = __Infer<typeof KickArenaMemberReducer>;
export type LeaveArenaRoomParams = __Infer<typeof LeaveArenaRoomReducer>;
export type LockArenaPowerupParams = __Infer<typeof LockArenaPowerupReducer>;
export type LogInParams = __Infer<typeof LogInReducer>;
export type LogOutParams = __Infer<typeof LogOutReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type RemoveFriendParams = __Infer<typeof RemoveFriendReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SendGameInviteParams = __Infer<typeof SendGameInviteReducer>;
export type SetPlayerActivityParams = __Infer<typeof SetPlayerActivityReducer>;
export type SignUpParams = __Infer<typeof SignUpReducer>;
export type StartArenaMatchParams = __Infer<typeof StartArenaMatchReducer>;
export type SubmitRoundResultParams = __Infer<typeof SubmitRoundResultReducer>;
export type TriggerArenaSabotageParams = __Infer<typeof TriggerArenaSabotageReducer>;
export type UnlockArenaPowerupParams = __Infer<typeof UnlockArenaPowerupReducer>;

